import type { Metadata } from "next";
import FormSingIn from "@/components/FormSingIn";
export const metadata: Metadata = {
  title: "Zendesk Auth",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/auth_google.ico",
    },
  },
};

const page = () => {
  return (
    <div>
      <FormSingIn />
    </div>
  );
};

export default page;
